### ISSUE TITLE
A tableview example would be nice

### ISSUE THREAD

**Issue by nasserprofessional** [seatgeek/SGImageCache#12]
It would be nice if there was an example of how to use it properly with a tableview and how to use the fast and slow queue for rows that are no longer on screen etc

**Comment by sobri909** [comment]
Funnily enough, I wrote a blog post specifically for answering those questions:

http://chairnerd.seatgeek.com/a-lightweight-ios-image-cache/

Let me know if there's any missing details I can fill in.

**Comment by sobri909** [comment]
Oh, just realised the blog post talks about using UIImage's memory cache. SGImageCache doesn't do that internally anymore. It uses its own memory cache, for greater control.

Another change since that blog post was written is the method signatures. SGImageCache uses PromiseKit instead of `thenDo:` completion blocks now. But the way you use the methods is still exactly the same.

**Comment by nasserprofessional** [comment]
Iv already seen the blog posts just making a suggestion as all other libraries that do the same have examples. If someone is going to use it they want to be able to download a working example try it out before they just go plugging things into their project. Now before anyone can even use it they have to first create thier own example and try it out first before they can decide if they want to use it or not because no example was provided. :/

**Comment by sobri909** [comment]
The library has three method calls.

```objc
[SGImageCache getImageForURL:url];

[SGImageCache slowGetImageForURL:url];

[SGImageCache moveTaskToSlowQueueForURL:url];
```

The blog post explains in detail the purpose of each.
